model = "Qwen/Qwen2.5-0.5B"

[env]
id = "primeintellect/continuation-quality"

[inference]
gpus = 6

[inference.args]
enforce_eager = true

[trainer]
gpus = 2

[trainer.args]
run_name = "continuation-quality"
micro_batch_size = 16
rollouts_per_example = 16
batch_size = 512
max_steps = 200
max_seq_len = 4096
