model = "Qwen/Qwen3-4B-Instruct-2507"

[env]
id = "will/wiki-search"

[env.args]
max_turns = 10

[inference]
gpus = 1

[inference.args]
enable_auto_tool_choice = true
tool_call_parser = "hermes"

[trainer]
gpus = 1

[trainer.args]
run_name = "wiki-search"
micro_batch_size = 2
rollouts_per_example = 16
batch_size = 512
max_steps = 500
max_tokens = 512
max_seq_len = 4096